# fly.toml app configuration file generated for django-business-management-practice on 2024-06-21T22:03:25+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'django-business-management-practice'
primary_region = 'hkg'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[[mounts]]
  source = 'data'
  destination = '/data'

[[services]]
  processes = ["app"]
  internal_port = 8000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[processes]
  cron = "supercronic /code/crontab" 
  app = ""

[[vm]]
  memory = '512'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
